name: observable_ish
description: Observable state and events for browser and Flutter.
version: 1.2.1
homepage: https://github.com/Jaguar-dart/observable_ish
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dev_dependencies:
  test: ^0.12.30
