name: observable_ish
description: |
  Write elegant reactive cross-platform client side application using observable states and event emitters.
version: 1.2.1
homepage: https://github.com/Jaguar-dart/observable_ish
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  collection: ^1.14.10

dev_dependencies:
  test: ^1.0.0
